### ISSUE TITLE
Use const here

### ISSUE THREAD

**Issue by joostf** [DanielvandeVelde/web-app-from-scratch-18-19#5]
And make the array immutable. It won't prevent you from updating its values..

https://github.com/DanielvandeVelde/web-app-from-scratch-18-19/blob/fa0992a77239e49cd48da3b440a323a8bd74cc61/week1/public/js/app.js#L1

**Comment by DanielvandeVelde** [comment]
I had trouble getting the data from the localStorage when beers is a const.  
I could push all the beers into the array, but then I would have an array in an array.
Using concat didn't work either since beers is already declared as a const.

There's probably a really smart way of doing this, but I'm not able to find it.
